services:
  - type: web
    name: flask-chat-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chat-db
          property: connectionString
    plan: free 